name=SerialConsoleEx
version=1.0.0
author=m1bcodes
maintainer=m1bcodes
sentence=Small and simple command line interface for Arduino with PuttyMode terminal support.
paragraph=Non-blocking serial command parsing with argument support, customizable configuration, and built-in help system. Works in Arduino IDE Serial Monitor or real terminals (PuTTY, VSCode). Optimized for low RAM usage on AVR boards.
category=Communication
url=https://github.com/m1bcodes/SerialConsoleEx.git
architectures=*
includes=SerialConsoleEx.h
